fixtures:
  repositories:
    stdlib:
        repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
        ref: 4.9.0
    vcsrepo:
        repo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo'
        ref: 1.3.1
  symlinks:
    vim: "#{source_dir}"
